name: Kivy Android Build
on: [push]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip python3-venv openjdk-17-jdk unzip git

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: Install Buildozer
      run: pip install buildozer

    - name: Build Android APK
      run: |
        buildozer init
        buildozer android debug

    - name: Store APK
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: bin/*.apk
