name: Build Android APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y openjdk-17-jdk unzip git zlib1g-dev

    - name: Install Buildozer
      run: pip install buildozer

    - name: Build APK with Buildozer
      run: |
        buildozer init
        buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: soundhunter-apk
        path: bin/*.apk
